# Generated by Django 5.0.6 on 2024-06-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0003_lojas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheBikes',
            fields=[
                ('opcao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bikcraft.bike', verbose_name='Opção Bike')),
                ('detalhe', models.CharField(max_length=255, verbose_name='Detalhe')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('opcao_lojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bikcraft.lojas', verbose_name='Nome da Loja')),
            ],
        ),
        migrations.AlterField(
            model_name='lojas',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome da Loja'),
        ),
    ]
