# Generated by Django 5.1 on 2024-08-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0007_alter_bike_foto_alter_detalhebikes_opcao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalheBikes',
        ),
    ]
