# Generated by Django 5.1 on 2024-08-22 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0008_delete_detalhebikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheBikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('detalhe', models.CharField(max_length=255, verbose_name='Detalhe')),
                ('bike', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikcraft.bike', verbose_name='Bike')),
            ],
        ),
    ]
