# Generated by Django 5.1 on 2024-09-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0009_detalhebikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bikes', models.IntegerField()),
                ('valor_total_bikes', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
