# Generated by Django 5.1 on 2024-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0010_bikeinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bikeinventory',
            name='numero_bikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikeinventory',
            name='valor_total_bikes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lojas',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.DeleteModel(
            name='DetalheBikes',
        ),
    ]
