# Generated by Django 5.0.6 on 2024-06-22 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikcraft', '0004_detalhebikes_pessoas_alter_lojas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhebikes',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoas',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalhebikes',
            name='opcao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikcraft.bike', verbose_name='Opção Bike'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='opcao_lojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikcraft.lojas', verbose_name='Opção da Loja'),
        ),
    ]
